---
### milestone 1 - Installing Fedora
# --volume: {{ FEDORA_HOME }}
# --volume: {{ FEDORA_HOME }}/data
# --volume: {{ FEDORA_HOME }}/server/config
- name: Install git
  apt:
    pkg: git
    state: present
    update_cache: true
    cache_valid_time: 86400

- name: "Download Fedora v{{ FEDORA_VERSION }}"
  get_url:
    url: "https://github.com/fcrepo3/fcrepo/releases/download/v{{ FEDORA_VERSION }}/fcrepo-installer-{{ FEDORA_VERSION }}.jar"
    dest: "/tmp/fcrepo-installer-{{ FEDORA_VERSION }}.jar"

- name: Prepare the local environment variables
  template:
    src: fedora-profile.sh.j2 
    dest: /etc/profile.d/fedora-profile.sh

- name: Create an "install.properties" file
  template:
    src: install.properties.j2 
    dest: /tmp/install.properties

- name: Install Fedora
  command: "java -jar /tmp/fcrepo-installer-{{ FEDORA_VERSION }}.jar /tmp/install.properties"
  args:
    chdir: /tmp/
    creates: "{{ TOMCAT_HOME }}/webapps/fedora.war"

- name: Set Permissions
  file: 
    path: "{{ item }}"
    owner: "{{ TOMCAT_USER }}" 
    group: "{{ TOMCAT_USER }}" 
    recurse: yes
  with_items:
    - "{{ TOMCAT_HOME }}/webapps"
    - "{{ FEDORA_HOME }}"

- name: Start tomcat
  service:
    name: "{{ TOMCAT_USER }}"
    state: restarted

- name: Wait for tomcat
  wait_for:
    path: "{{ FEDORA_HOME }}/data/fedora-xacml-policies/repository-policies/default/deny-apim-if-not-localhost.xml"

- name: Download / Clone the Islandora specific XACML policies
  git:
    repo: https://github.com/Islandora/islandora-xacml-policies.git
    dest: "{{ FEDORA_HOME }}/data/fedora-xacml-policies/repository-policies/islandora"
    update: no

- name: Remove the deny-purge policies and the anonymous-user policies
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ FEDORA_HOME }}/data/fedora-xacml-policies/repository-policies/default/deny-purge-datastream-if-active-or-inactive.xml"
    - "{{ FEDORA_HOME }}/data/fedora-xacml-policies/repository-policies/default/deny-purge-object-if-active-or-inactive.xml"
    - "{{ FEDORA_HOME }}/data/fedora-xacml-policies/repository-policies/islandora/permit-apim-to-anonymous-user.xml"
    - "{{ FEDORA_HOME }}/data/fedora-xacml-policies/repository-policies/islandora/permit-upload-to-anonymous-user.xml"

- name: Giving access to Fedora
  lineinfile: 
    line: "            <AttributeValue DataType=\"http://www.w3.org/2001/XMLSchema#string\">{{ item }}</AttributeValue>"
    insertafter: "            <AttributeValue DataType=\"http://www.w3.org/2001/XMLSchema#string\">127.0.0.1</AttributeValue>"
    dest: "{{ FEDORA_HOME }}/data/fedora-xacml-policies/repository-policies/default/deny-apim-if-not-localhost.xml"
  with_items: "{{ IP_TO_ACCESS_FEDORA }}"

### milestone 3 - Installing & Configuring Drupal Filter
- name: "Download the Latest Version of the Islandora Drupal Filter"
  get_url:
    url: "https://github.com/Islandora/islandora_drupal_filter/releases/download/v7.1.3/fcrepo-drupalauthfilter-3.8.1.jar"
    dest: "{{ TOMCAT_HOME }}/webapps/fedora/WEB-INF/lib/fcrepo-drupalauthfilter-3.8.1.jar"

- name: "Make the Fedora Repository Aware of the New Filter"
  copy:
    src: jaas.conf
    dest: "{{ FEDORA_HOME }}/server/config/jaas.conf"

- name: Making sure that tomcat is down...
  command: "pkill java"

- name: Set Permissions
  file: 
    path: "{{ item }}"
    owner: "{{ TOMCAT_USER }}" 
    group: "{{ TOMCAT_USER }}" 
    recurse: yes
  with_items:
    - "{{ TOMCAT_HOME }}/webapps"
    - "{{ FEDORA_HOME }}"

- name: "Configure the new filter to connect to Drupal (filter-drupal.xml)"
  template: 
    src: filter-drupal.xml.j2
    dest: "{{ FEDORA_HOME }}/server/config/filter-drupal.xml"
    owner: "www-data"

### milestone 6 - Installing Solr
- name: Configure fedoraAdmin in fedora-users.xml
  replace: 
    dest: "{{ FEDORA_HOME }}/server/config/fedora-users.xml"
    regexp: 'user name="fedoraAdmin" password="fedoraAdmin"'
    replace: "user name=\"{{ FEDORA_DATABASE_USER }}\" password=\"{{ FEDORA_DATABASE_PASSWORD }}\""

- name: Configure fgsAdmin in fedora-users.xml
  blockinfile: 
    dest: "{{ FEDORA_HOME }}/server/config/fedora-users.xml"
    block: |
      <user name="{{ FGSADMIN_USER }}" password="{{ FGSADMIN_PASSWORD }}">
        <attribute name="fedoraRole">
          <value>administrator</value>
        </attribute>
      </user>

- name: Start tomcat
  service:
    name: "{{ TOMCAT_USER }}"
    state: restarted

- name: Wait for tomcat
  wait_for:
    path: "{{ TOMCAT_HOME }}/logs/catalina.out"
    search_regex: "INFO: Server startup in"

