---
# tasks file for start-fedora
- name: Create the init script in /etc/init.d/tomcat7
  template:
    src: tomcat7.j2
    dest: /etc/init.d/tomcat7
    mode: "u=rwx,g=rx,o=rx"

- name: Set Permissions
  file: 
    path: "{{ item }}"
    owner: "{{ TOMCAT_USER }}" 
    group: "{{ TOMCAT_USER }}" 
    recurse: yes
  with_items:
    - "{{ TOMCAT_HOME }}/webapps"
    - "{{ FEDORA_HOME }}"

- name: Restart tomcat
  service:
    name: tomcat7
    state: restarted
  ignore_errors: True

- name: Wait for tomcat
  wait_for:
    path: "{{ TOMCAT_HOME }}/logs/catalina.out"
    search_regex: "INFO: Server startup in"

